create table if not exists agent_reports (
  id bigint generated by default as identity primary key,
  agent_name text not null,
  symbol text,
  status text,
  message text,
  payload jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists signals (
  id bigint generated by default as identity primary key,
  symbol text check (symbol in ('BTC','GOLD')),
  action text check (action in ('BUY','SELL','HOLD')),
  entry numeric,
  sl numeric,
  tp numeric,
  confidence numeric,
  reason text,
  agent_name text,
  status text default 'pending',
  approved_by text,
  created_at timestamptz default now(),
  approved_at timestamptz
);

create index if not exists idx_signals_symbol_status
  on signals (symbol, status, created_at desc);

create index if not exists idx_reports_created
  on agent_reports (created_at desc);

alter table signals enable row level security;
alter table agent_reports enable row level security;

drop policy if exists "anon read signals" on signals;
create policy "anon read signals" on signals for select using (true);

drop policy if exists "anon update signals" on signals;
create policy "anon update signals" on signals for update using (true);

drop policy if exists "anon read reports" on agent_reports;
create policy "anon read reports" on agent_reports for select using (true);

drop policy if exists "anon insert reports" on agent_reports;
create policy "anon insert reports" on agent_reports for insert with check (true);
